---
version: '3'
services:
  minio:
    read_only: true
    image: quay.io/minio/minio:RELEASE.2024-10-02T17-50-41Z
    command: ["server", "/data", "--console-address", ":9001"]
    ports:
      - 9000:9000
      - 9001:9001
    networks:
      - app_net

  mongodb:
    image: mongo:8.0.1
    container_name: mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongodbuser
      MONGO_INITDB_ROOT_PASSWORD: 123456
      MONGO_INITDB_DATABASE: appdb
      MONDODB_LOG_DIR: /dev/null
      MONGODB_DATA_DIR: /data/db
    volumes:
      - ./db_initializer:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
    networks:
      - app_net
  
networks:
  app_net:
